// <auto-generated />
using System;
using Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Core.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalystId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnalystId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Core.Models.FeedbackCategory", b =>
                {
                    b.Property<int>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("FeedbackCategories");
                });

            modelBuilder.Entity("Core.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("AuthorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 29, 16, 13, 57, 796, DateTimeKind.Unspecified).AddTicks(7725),
                            FullName = "Default Admin",
                            IsActive = true,
                            Login = "admin",
                            Password = "5F5jIUbfnYve1P8kbEkrvQ==",
                            PhoneNumber = "000-000-0000",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Тетяна Шевченко",
                            IsActive = true,
                            Login = "tetyana_shevchenko",
                            Password = "4Qu2+aaPw/wSqe0wto3aKQ==",
                            PhoneNumber = "+380679876543",
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Андрій Бондаренко",
                            IsActive = true,
                            Login = "andriy_bondarenko",
                            Password = "2mJreKybkcVOXnk5B9yyFQ==",
                            PhoneNumber = "+380931112233",
                            Role = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 20, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Марина Лисенко",
                            IsActive = true,
                            Login = "maryna_lysenko",
                            Password = "pBA4YdaPn3oSjNkftwEFmA==",
                            PhoneNumber = "+380665554433",
                            Role = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 28, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Сергій Мельник",
                            IsActive = false,
                            Login = "serhiy_melnyk",
                            Password = "DuSHAjw8F/LbWuvIL6FjtA==",
                            PhoneNumber = "+380970001122",
                            Role = 3
                        });
                });

            modelBuilder.Entity("Core.Models.Feedback", b =>
                {
                    b.HasOne("Core.Models.User", "Analyst")
                        .WithMany()
                        .HasForeignKey("AnalystId");

                    b.Navigation("Analyst");
                });

            modelBuilder.Entity("Core.Models.FeedbackCategory", b =>
                {
                    b.HasOne("Core.Models.Category", "Category")
                        .WithMany("FeedbackCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Feedback", "Feedback")
                        .WithMany("FeedbackCategories")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("Core.Models.Log", b =>
                {
                    b.HasOne("Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Models.Category", b =>
                {
                    b.Navigation("FeedbackCategories");
                });

            modelBuilder.Entity("Core.Models.Feedback", b =>
                {
                    b.Navigation("FeedbackCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
