"""unit

Revision ID: b50b3c78dcb3
Revises: change_steps_to_json
Create Date: 2025-05-27 20:08:58.271062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50b3c78dcb3'
down_revision: Union[str, None] = 'change_steps_to_json'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('unit', sa.String(length=25), nullable=False))
    op.alter_column('recipes', 'steps',
               existing_type=sa.TEXT(),
               type_=sa.ARRAY(sa.String(length=255)),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'steps',
               existing_type=sa.ARRAY(sa.String(length=255)),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('ingredients', 'unit')
    # ### end Alembic commands ###
