"""ondelete

Revision ID: 6a1b4404df75
Revises: 76b8db5ba5db
Create Date: 2025-06-13 20:46:14.059444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1b4404df75'
down_revision: Union[str, None] = '76b8db5ba5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sets_categories_association_set_id_fkey', 'sets_categories_association', type_='foreignkey')
    op.drop_constraint('sets_categories_association_category_id_fkey', 'sets_categories_association', type_='foreignkey')
    op.create_foreign_key(None, 'sets_categories_association', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sets_categories_association', 'sets', ['set_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sets_categories_association', type_='foreignkey')
    op.drop_constraint(None, 'sets_categories_association', type_='foreignkey')
    op.create_foreign_key('sets_categories_association_category_id_fkey', 'sets_categories_association', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('sets_categories_association_set_id_fkey', 'sets_categories_association', 'sets', ['set_id'], ['id'])
    # ### end Alembic commands ###
